###########
# site.url, site.title

url:   'http://dotcoma.github.io'
title: 'What Happened To Advertising'


########
# more settings

markdown: kramdown

sass:
  sass_dir: css
  style:    expanded



exclude:
- README.md


safe: true
lsi: false

